"""add is_platform_admin to users

Revision ID: a554ec9a3677
Revises: e9cbe5b0f249
Create Date: 2026-08-31 19:02:48.502482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a554ec9a3677'
down_revision: Union[str, None] = 'e9cbe5b0f249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_admin')
    # ### end Alembic commands ###
